/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 GarageGLB4.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('https://cdn.shopify.com/s/files/1/0730/4432/8734/files/GarageGLB4.glb?v=1690125630')
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, -Math.PI / 2, 0]} position={[-1.6, -3, 5.3]} scale={0.015} >
        <mesh castShadow receiveShadow geometry={nodes.Box976.geometry} material={materials.Default} position={[350, 150, -703.949]} rotation={[-1.57, 0, 0]} scale={2.54} />
        <mesh castShadow receiveShadow geometry={nodes.Object001.geometry} material={materials['17 - Default,']} position={[70.056, 138.731, -545.95]} rotation={[-1.57, 0, 0]} scale={2.54} />
        <mesh castShadow receiveShadow geometry={nodes.Ground44f.geometry} material={materials['15 - Default']} position={[340.839, 65.555, 507.607]} rotation={[-1.459, 0, 0]} scale={2.54} />
        <mesh castShadow receiveShadow geometry={nodes.Object088.geometry} material={materials['15 - Default']} position={[-86.242, 153.684, 140.348]} rotation={[-1.459, 0.004, 0.035]} scale={2.54} />
        <mesh castShadow receiveShadow geometry={nodes.Pool_border_low.geometry} material={materials['15 - Default2']} position={[-288.802, 165.687, -330.362]} rotation={[-1.57, 0, 0]} scale={2.54} />
        <mesh castShadow receiveShadow geometry={nodes.Stone_wall_1_low.geometry} material={materials['15 - Default1']} position={[-227.951, 197.751, -935.038]} rotation={[-1.57, 0, 0]} scale={2.54} />
        <mesh castShadow receiveShadow geometry={nodes.Object090.geometry} material={materials['15 - Default']} position={[-212.647, 153.684, 148.273]} rotation={[-1.459, 0.004, 0.035]} scale={2.54} />
        <mesh castShadow receiveShadow geometry={nodes.Object091.geometry} material={materials['15 - Default']} position={[-344.714, 153.684, 151.165]} rotation={[-1.459, 0.004, 0.035]} scale={2.54} />
        <mesh castShadow receiveShadow geometry={nodes.Object089.geometry} material={materials['15 - Default']} position={[340.839, 65.555, 507.607]} rotation={[-1.459, 0, 0]} scale={2.54} />
        <mesh castShadow receiveShadow geometry={nodes.Object093.geometry} material={materials['15 - Default']} position={[340.839, 65.555, 507.607]} rotation={[-1.459, 0, 0]} scale={2.54} />
        <mesh castShadow receiveShadow geometry={nodes.Object094.geometry} material={materials['15 - Default']} position={[340.839, 65.555, 507.607]} rotation={[-1.459, 0, 0]} scale={2.54} />
        <mesh castShadow receiveShadow geometry={nodes.Object095.geometry} material={materials['15 - Default']} position={[-488.007, 153.684, 155.579]} rotation={[-1.459, 0.004, 0.035]} scale={2.54} />
      </group>
    </group>
  )
}

useGLTF.preload('https://cdn.shopify.com/s/files/1/0730/4432/8734/files/GarageGLB4.glb?v=1690125630')
