/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 model.glb
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Pump(props) {
  const { nodes, materials } = useGLTF('https://cdn.shopify.com/s/files/1/0730/4432/8734/files/model.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, -Math.PI / 2, 0]} position={[3.185, 1.08, 5.042]} scale={0.015} >
        <mesh geometry={nodes.PumpingStation.geometry} material={materials.Default} rotation={[-Math.PI / 2, 0, 0]} castShadow receiveShadow />
      </group>
    </group>
  )
}

useGLTF.preload('https://cdn.shopify.com/s/files/1/0730/4432/8734/files/model.glb')
