/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 tube.glb
*/

import React, { useRef } from 'react'
import { MeshWobbleMaterial, useGLTF } from "@react-three/drei"

export function Tubes(props) {
  const { nodes, materials } = useGLTF('https://cdn.shopify.com/s/files/1/0730/4432/8734/files/tube.glb?v=1690143568')
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, -Math.PI / 2, 0]} position={[-1.6, -3.0, 5.3]} scale={1.5} >
        <mesh geometry={nodes.Line002.geometry} position={[0.754, 2.023, -6.318]} >
          <MeshWobbleMaterial
            attach="material"
            factor={0.01}
            speed={10}
            color={"lightblue"}
            opacity={0.6}
            transparent
          />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('https://cdn.shopify.com/s/files/1/0730/4432/8734/files/tube.glb?v=1690143568')
